version: '3.1'

services:
  mysql-database:    
    image: mysql/mysql-server:latest
    ports: [3306:3306]
    hostname: mysqlprod
    environment:
        MYSQL_ROOT_PASSWORD: mysqlpass
        MYSQL_USER: maia
        MYSQL_PASSWORD: mysqlpass
        MYSQL_DATABASE: oxygent
  mysql-database-testing:    
    image: mysql/mysql-server:latest
    ports: [3307:3306]
    hostname: mysqltesting
    environment:
        MYSQL_ROOT_PASSWORD: mysqlpass
        MYSQL_USER: maia
        MYSQL_PASSWORD: mysqlpass
        MYSQL_DATABASE: test
  backend:
    image: node:16-alpine
    user: root
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
    volumes:
      [./back/:/home/node/app]
    expose:
      [3000]
    ports:
      [3000:3000]
    command: npm start
    depends_on:
      [mysql-database, mysql-database-testing]
  frontend:
    image: node:16-alpine
    user: root
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
    volumes:
      [./front/:/home/node/app]
    expose:
      [3006]
    ports: [3006:3006]
    command: npm start